<?php

/**
 * BaseApplicationSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $ApplicationSource
 * 
 * @method integer                     getId()                Returns the current record's "id" value
 * @method string                      getName()              Returns the current record's "name" value
 * @method description                 getDescription()       Returns the current record's "description" value
 * @method Doctrine_Collection         getApplicationSource() Returns the current record's "getApplicationSource" collection
 * @method ApplicationSource           setId()                Sets the current record's "id" value
 * @method ApplicationSource           setName()              Sets the current record's "name" value
 * @method ApplicationSource           setDescription()       Sets the current record's "description" value
 * @method ApplicationSource           setApplicationSource() Sets the current record's "getApplicationSource" collection
 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApplicationSource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_application_source');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 2147483647, array(
             'type' => 'string',
             'length' => 2147483647,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ApplicationSource', array(
             'local' => 'id',
             'foreign' => 'applicationSourceId'));
    }
}