<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/03/30 08:34:06
sfConfig::add(array(
  'mod_recruitmentapply_enabled' => true,
  'mod_recruitmentapply_view_class' => 'sfPHP',
));
