<?php

/**
 * PluginDayName class file
 */

/**
 * PluginDayName
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginDayName extends BaseDayName
{

	/*public function getCurrencyList(){
		
		$service = new DayNameService();
		$currencyList = $service->getCurrencyListByDayNameId($this->getId());
		$temp = array();
		
		foreach ($currencyList as $currency) {
			$temp[] = __($currency->getCurrencyType()->getCurrencyName());
		}
		return implode(',', $temp);
	}*/
}