<?php

/**
 * PluginApplicationSource class file
 */

/**
 * PluginApplicationSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin\plugin
 */
abstract class PluginApplicationSource extends BaseApplicationSource
{

}