<?php

/**
 * PluginApplicationSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginApplicationSourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginApplicationSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginApplicationSource');
    }
}