<?php

/**
 *  ApplicationSource class file
 */

/**
 * ApplicationSource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin
 */
class ApplicationSource extends PluginApplicationSource
{
}
