<?php

/**
 * ApplicationSourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicationSourceTable extends PluginApplicationSourceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApplicationSourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApplicationSource');
    }
}