<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/02/12 16:26:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=hrisdb',
  'username' => 'root',
  'password' => '',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
