<?php

/**
 * EmpWorkShift class file
 */

/**
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\pim
 */
class EmpWorkShift extends PluginEmpWorkShift
{
}
