<?php

/**
 * EmpFamilyMemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpFamilyMemberTable extends PluginEmpFamilyMemberTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpFamilyMemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmpFamilyMember');
    }
}