<?php

/**
 * BaseEmployeeCharacterReference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $emp_number
 * @property decimal $seqno
 * @property string $name
 * @property string $relation
 * @property string $company
 * @property string $position
 * @property string $contact_number
 *
 * @method integer                          getEmpNumber()          Returns the current record's "emp_number" value
 * @method decimal                          getSeqno()              Returns the current record's "seqno" value
 * @method string                           getName()               Returns the current record's "name" value
 * @method string                           getRelation()           Returns the current record's "relation" value
 * @method string                           getCompany()            Returns the current record's "company" value
 * @method string                           getPosition()           Returns the current record's "position" value
 * @method Employee                         getEmployee()           Returns the current record's "Employee" value
 * @method string                           getContactNumber()      Returns the current record's "Contact Number" value
 * @method EmployeeCharacterReference       setEmpNumber()          Sets the current record's "emp_number" value
 * @method EmployeeCharacterReference       setSeqno()              Sets the current record's "seqno" value
 * @method EmployeeCharacterReference       setName()               Sets the current record's "name" value
 * @method EmployeeCharacterReference       setRelation()           Sets the current record's "relation" value
 * @method EmployeeCharacterReference       setCompany()            Sets the current record's "company" value
 * @method EmployeeCharacterReference       setEmployee()           Sets the current record's "Employee" value
 * @method EmployeeCharacterReference       setContactNumber()      Sets the current record's "Contact Number" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmployeeCharacterReference extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_character_reference');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('ecr_seqno as seqno', 'decimal', 10, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => 10,
             ));
        $this->hasColumn('ecr_name as name', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('ecr_relation as relation', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('ecr_company as company', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('ecr_position as position', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ecr_contact_number as contact_number', 'varchar', 30, array(
             'type' => 'varchar',
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}