<?php

/**
 * BaseDayName
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $day_name
 * 
 * @method integer            getId()               Returns the current record's "id" value
 * @method string             getDayName()          Returns the current record's "day_name" value
 * @method string             getShortDayName()     Returns the current record's "short_day_name" value
 * @method DayName            setId()               Sets the current record's "id" value
 * @method DayName            setDayName()          Sets the current record's "day_name" value
 * @method DayName            setShortDayName()     Sets the current record's "short_day_name" value
 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDayName extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_day_name');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('day_name', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('short_day_name', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
    }

    /*public function setUp()
    {
        parent::setUp();
        $this->hasMany('EmployeeSalary', array(
             'local' => 'id',
             'foreign' => 'payGradeId'));

        $this->hasMany('DayNameCurrency', array(
             'local' => 'id',
             'foreign' => 'pay_grade_id'));
    }*/
}