<?php

/**
 * DayName class file
 */

/**
 * DayName
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\admin
 */
class DayName extends PluginDayName
{
}
