<?php

/**
 * PluginEmpWorkShiftTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmpWorkShiftTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmployeeWorkShiftTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmpWorkShift');
    }
}