<?php

/**
 * PluginEmpWorkShift class file
 */

/**
 * PluginEmpWorkShift
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm
 * @subpackage model\pim\plugin
 */
abstract class PluginEmpWorkShift extends BaseEmpWorkShift
{

}