<?php

/**
 * PluginHolidayTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHolidayTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginHolidayTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginHolidayType');
    }
}